artifact_location: file:///C:/Users/Miguel/Desktop/EstudosUTFPR/Vis%C3%A3o%20Computacional/projeto%202/Machine_Learning/mlruns_ml/0
creation_time: 1782871404864
experiment_id: '0'
last_update_time: 1782871404864
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
