artifact_location: file:///C:/Users/Miguel/Desktop/EstudosUTFPR/Vis%C3%A3o%20Computacional/projeto%202/Machine_Learning/mlruns_ml/449545538337494323
creation_time: 1782871404885
experiment_id: '449545538337494323'
last_update_time: 1782871404885
lifecycle_stage: active
name: Projeto2_MachineLearning
trace_location: null
workspace: default
